
---
version: '3.0'

services:
  frontend:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - 8080:80
  backend:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - 5000:5000
  redis:
    image: redis:3.2-alpine
    command: redis-server
    volumes:
      - ./data:/data
    expose:
      - 6379